name: Tests (wp-env)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm ci || npm install

      - name: Start wp-env
        run: npm run wp-env:start

      - name: Run tests in wp-env
        run: npm run test:env

      - name: Stop wp-env
        if: always()
        run: npm run wp-env:stop
