name: PHPUnit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '8.1' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        run: |
          composer install --no-interaction --no-progress --prefer-dist

      - name: Run unit tests (WP_Mock)
        run: |
          composer test:unit

      - name: Start MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.7'
          mysql root password: 'root'
          mysql database: 'wordpress_test'

      - name: Wait for MySQL
        run: |
          for i in `seq 1 30`; do
            (echo > /dev/tcp/127.0.0.1/3306) >/dev/null 2>&1 && break
            sleep 1
          done

      - name: Run wp-phpunit tests
        env:
          DB_NAME: wordpress_test
          DB_USER: root
          DB_PASSWORD: root
          DB_HOST: 127.0.0.1
        run: |
          composer test:wp
